# -*- coding: utf-8 -*-
"""Unit2_L3_Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/muktasidrahman/bc7cda85a98fc3399be6699c04118077/unit2_l3_lists.ipynb
"""

#Name: Muktasid Rahman
#Lesson 3: Working with Lists

# 1)Create a list of 5 of your favorite tv shows.  
favorite_shows = ['The Office','Prison Break','Friends', 'Ozark','Narcos']

# 2)Print the list in its original order.
print(favorite_shows)

# 3) Use the sorted() function to print the list in alphabetical order.  How is sorted() different from sort()?
sorted(favorite_shows)

# 4)Print out your original list.
print(favorite_shows)

# 5) Used sorted() to print your list in reverse alphabetical order.

sorted(favorite_shows,reverse=True)

# 6) Create a message indicating how many favorite TV shows you have – use the len() function.
print(len(favorite_shows))

